/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Liveness
         * @description Answer 200 without touching any dependency.
         */
        get: operations["read_liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Readiness
         * @description Answer 200 when Postgres answers within the deadline, and 503 otherwise.
         */
        get: operations["read_readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Users
         * @description Answer one page of users, oldest first, with the total and the bounds applied.
         */
        get: operations["read_users_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset
         * @description Enqueue the reset email and answer 200, whether or not an account uses the address.
         *
         *     The route never looks the address up. The job does, in the worker, so the response and the
         *     work this request causes are identical for a known and an unknown address (B-14).
         */
        post: operations["request_password_reset_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Open a session for an existing account and set the session cookie.
         */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the session if there is one, and clear the cookie either way.
         *
         *     No injected `Response` is declared. FastAPI assigns a returned `Response` instance directly
         *     and never merges the injected one's headers, so anything written to it here would be dropped
         *     without a test noticing, on the one route whose whole job is to get a cookie header right.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Answer the signed-in user's identity and role, and 401 without a usable session.
         */
        get: operations["read_me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change My Password
         * @description Replace the password after proving the current one, signing out every other session.
         */
        patch: operations["change_my_password_v1_auth_me_patch"];
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account, sign it in, and set the session cookie.
         */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password With Token
         * @description Set a new password from an emailed token and sign the account out everywhere.
         */
        post: operations["reset_password_with_token_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout
         * @description Create a subscription Checkout session for the signed-in user; answer its URL.
         */
        post: operations["create_checkout_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Portal
         * @description Open the billing portal for the signed-in user's Stripe customer; answer its URL.
         */
        post: operations["create_portal_v1_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Webhook
         * @description Verify a Stripe delivery against its raw bytes and apply it at most once.
         *
         *     The body is read as bytes and never parsed before the signature is checked, because any
         *     re-serialization would change the bytes Stripe signed. No session and no CSRF header are
         *     involved: Stripe sends neither, and the signature is what authenticates the request.
         */
        post: operations["receive_webhook_v1_billing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Presigned Upload
         * @description Answer a URL the browser can PUT the file to within fifteen minutes.
         */
        post: operations["create_presigned_upload_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUserData
         * @description One user as an administrator sees it: never the password hash.
         */
        AdminUserData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * AdminUserListResponse
         * @description The `{ data, meta }` envelope around one page of users.
         */
        AdminUserListResponse: {
            /** Data */
            data: components["schemas"]["AdminUserData"][];
            meta: components["schemas"]["PageMeta"];
        };
        /**
         * AuthenticatedUserData
         * @description The signed-in user, carrying only what a client may see: the id, address, and role.
         */
        AuthenticatedUserData: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * AuthenticatedUserResponse
         * @description The `{ data }` envelope every successful auth route answers with.
         */
        AuthenticatedUserResponse: {
            data: components["schemas"]["AuthenticatedUserData"];
        };
        /**
         * BillingRedirectData
         * @description The hosted Stripe page the browser is sent to next.
         */
        BillingRedirectData: {
            /** Url */
            url: string;
        };
        /**
         * BillingRedirectResponse
         * @description The `{ data }` envelope around a Checkout or portal URL.
         */
        BillingRedirectResponse: {
            data: components["schemas"]["BillingRedirectData"];
        };
        /**
         * ChangePasswordRequest
         * @description The body of a password change, which proves the caller knows the current password.
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * CheckoutCreate
         * @description The body of `POST /v1/billing/checkout`: the Stripe price to subscribe to.
         */
        CheckoutCreate: {
            /** Price Id */
            price_id: string;
        };
        /**
         * ErrorCode
         * @description Every error code this application answers with, namespaced DOMAIN_REASON.
         * @enum {string}
         */
        ErrorCode: "AUTH_ADMIN_REQUIRED" | "AUTH_INVALID_CREDENTIALS" | "AUTH_REQUIRED" | "AUTH_SESSION_EXPIRED" | "AUTH_EMAIL_ALREADY_REGISTERED" | "AUTH_RESET_TOKEN_INVALID" | "BILLING_NO_ACCOUNT" | "BILLING_NOT_CONFIGURED" | "BILLING_WEBHOOK_MISCONFIGURED" | "BILLING_WEBHOOK_INVALID_SIGNATURE" | "BILLING_WEBHOOK_PROCESSING_FAILED" | "CSRF_HEADER_MISSING" | "IDEMPOTENCY_KEY_IN_PROGRESS" | "IDEMPOTENCY_KEY_REUSED" | "INPUT_PAYLOAD_TOO_LARGE" | "INPUT_VALIDATION_ERROR" | "RATE_LIMIT_EXCEEDED" | "ROUTING_METHOD_NOT_ALLOWED" | "ROUTING_NOT_FOUND" | "SERVER_DATABASE_UNAVAILABLE" | "SERVER_INTERNAL_ERROR" | "SERVER_RATE_LIMIT_UNAVAILABLE" | "SERVER_REQUEST_TIMEOUT" | "UPLOADS_STORAGE_UNCONFIGURED";
        /**
         * ErrorResponse
         * @description One failed request: a registry code the client switches on and a human-readable message.
         *
         *     `field_errors` is populated only for `INPUT_VALIDATION_ERROR` and omitted from the body
         *     entirely otherwise, so every other failure keeps the two-key shape clients already handle. It
         *     exists because a form has to show a message beside the input it belongs to, and the prose
         *     `error` string is documented as never parsed; reading the field out of it would make a
         *     human-readable sentence into an interface.
         */
        ErrorResponse: {
            /** @description Machine-readable code from the error registry. */
            code: components["schemas"]["ErrorCode"];
            /**
             * Error
             * @description Human-readable message; never parsed by clients.
             */
            error: string;
            /**
             * Field Errors
             * @description Per-field validation failures, present only for a 400.
             */
            field_errors?: components["schemas"]["FieldError"][] | null;
        };
        /**
         * FieldError
         * @description One field of a request body that failed validation, and why.
         */
        FieldError: {
            /**
             * Field
             * @description The offending field, as a dotted path without the body prefix.
             */
            field: string;
            /**
             * Message
             * @description Why this field was rejected.
             */
            message: string;
        };
        /**
         * ForgotPasswordData
         * @description The confirmation a reset request answers with, identical for every address.
         */
        ForgotPasswordData: {
            /** Message */
            message: string;
        };
        /**
         * ForgotPasswordRequest
         * @description The body of a reset request.
         *
         *     The email carries no pattern, for the reason `LoginRequest` gives: the answer is the same 200
         *     for every address, and a 400 for one that is not even registrable would be the one response
         *     that differed.
         */
        ForgotPasswordRequest: {
            /** Email */
            email: string;
        };
        /**
         * ForgotPasswordResponse
         * @description The `{ data }` envelope of a reset request.
         */
        ForgotPasswordResponse: {
            data: components["schemas"]["ForgotPasswordData"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthLiveness
         * @description Body of `GET /health`: the process is up.
         */
        HealthLiveness: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * HealthReadiness
         * @description Body of `GET /health/ready`: whether Postgres answered within the deadline.
         */
        HealthReadiness: {
            /**
             * Db
             * @enum {string}
             */
            db: "connected" | "disconnected";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * LoginRequest
         * @description The body of a sign-in.
         *
         *     The email carries no pattern. A malformed address is a failed sign-in rather than a malformed
         *     request, and answering 400 here would tell a caller that an address is not even registrable,
         *     which is one more bit than a sign-in should reveal.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PageMeta
         * @description Where a page sits in the whole list: the total, and the bounds that produced this page.
         */
        PageMeta: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PresignUploadRequest
         * @description What the client wants to upload: its purpose and its file extension.
         */
        PresignUploadRequest: {
            /** Extension */
            extension: string;
            purpose: components["schemas"]["UploadPurpose"];
        };
        /**
         * PresignedUploadData
         * @description Everything the browser needs to PUT the file straight to R2.
         */
        PresignedUploadData: {
            /** Content Type */
            content_type: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Key */
            key: string;
            /**
             * Method
             * @default PUT
             * @constant
             */
            method: "PUT";
            /** Upload Url */
            upload_url: string;
        };
        /**
         * PresignedUploadResponse
         * @description The success envelope for a presigned upload.
         */
        PresignedUploadResponse: {
            data: components["schemas"]["PresignedUploadData"];
        };
        /**
         * RegisterRequest
         * @description The body of a registration.
         */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ResetPasswordRequest
         * @description The body of a reset: the token from the email's link and the new password.
         *
         *     The password takes registration's constraints, since it becomes the account's password on
         *     exactly the same terms. The token's ceiling is generous against the 43 characters a real one
         *     has, and exists so an oversized value is refused before it is hashed.
         */
        ResetPasswordRequest: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /**
         * UploadPurpose
         * @description What the uploaded file is for; each purpose has its own extension allowlist.
         * @enum {string}
         */
        UploadPurpose: "avatar";
        /**
         * UserRole
         * @description Every role the `user_role` enum holds, in its declared order.
         * @enum {string}
         */
        UserRole: "member" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebhookReceivedData
         * @description The acknowledgement Stripe needs: any 2xx stops its retries.
         */
        WebhookReceivedData: {
            /** Received */
            received: boolean;
        };
        /**
         * WebhookReceivedResponse
         * @description The `{ data }` envelope around the webhook's acknowledgement.
         */
        WebhookReceivedResponse: {
            data: components["schemas"]["WebhookReceivedData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLiveness"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadiness"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Postgres did not answer within the deadline */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadiness"];
                };
            };
        };
    };
    read_users_v1_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    request_password_reset_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_my_password_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_password_with_token_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_checkout_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingRedirectResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_portal_v1_billing_portal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingRedirectResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    receive_webhook_v1_billing_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookReceivedResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The event could not be processed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_presigned_upload_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUploadResponse"];
                };
            };
            /** @description The request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
