/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/health': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Liveness
         * @description Answer 200 without touching any dependency.
         */
        get: operations['read_liveness_health_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/health/ready': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Readiness
         * @description Answer 200 when Postgres answers within the deadline, and 503 otherwise.
         */
        get: operations['read_readiness_health_ready_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthLiveness
         * @description Body of `GET /health`: the process is up.
         */
        HealthLiveness: {
            /**
             * Status
             * @constant
             */
            status: 'ok';
        };
        /**
         * HealthReadiness
         * @description Body of `GET /health/ready`: whether Postgres answered within the deadline.
         */
        HealthReadiness: {
            /**
             * Db
             * @enum {string}
             */
            db: 'connected' | 'disconnected';
            /**
             * Status
             * @enum {string}
             */
            status: 'ok' | 'degraded';
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HealthLiveness'];
                };
            };
        };
    };
    read_readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HealthReadiness'];
                };
            };
        };
    };
}
