"""Create the set_updated_at trigger function, the users table, its unique index, and its trigger.

Written by hand rather than from an autogenerated draft, because autogenerate produces none of the
three things that matter here: a PL/pgSQL function, a unique index over an expression, and a
trigger. The function is created in this first revision rather than beside the first table that
happens to need it, because every table that follows reuses it.

Revision ID: 20260923_0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "20260923_0001"
down_revision = None
branch_labels = None
depends_on = None

TRIGGER_FUNCTION_NAME = "set_updated_at"
USERS_TABLE_NAME = "users"
USERS_TRIGGER_NAME = "users_set_updated_at"
LOWER_EMAIL_INDEX_NAME = "ix_users_lower_email"

# `now()` is the transaction timestamp, which is what the column should carry: every row written
# by one transaction shares an instant, and a statement inside it cannot appear to precede another.
CREATE_TRIGGER_FUNCTION = f"""
CREATE OR REPLACE FUNCTION {TRIGGER_FUNCTION_NAME}() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""
DROP_TRIGGER_FUNCTION = f"DROP FUNCTION IF EXISTS {TRIGGER_FUNCTION_NAME}()"
CREATE_LOWER_EMAIL_INDEX = (
    f"CREATE UNIQUE INDEX {LOWER_EMAIL_INDEX_NAME} ON {USERS_TABLE_NAME} (lower(email))"
)
CREATE_USERS_TRIGGER = f"""
CREATE TRIGGER {USERS_TRIGGER_NAME}
BEFORE UPDATE ON {USERS_TABLE_NAME}
FOR EACH ROW EXECUTE FUNCTION {TRIGGER_FUNCTION_NAME}()
"""
DROP_USERS_TRIGGER = f"DROP TRIGGER IF EXISTS {USERS_TRIGGER_NAME} ON {USERS_TABLE_NAME}"


def upgrade() -> None:
    """Create the shared trigger function, then the table, its unique index, and its trigger."""
    op.execute(CREATE_TRIGGER_FUNCTION)
    op.create_table(
        USERS_TABLE_NAME,
        sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.execute(CREATE_LOWER_EMAIL_INDEX)
    op.execute(CREATE_USERS_TRIGGER)


def downgrade() -> None:
    """Undo the revision in reverse, leaving neither the table nor the shared function behind.

    The index goes with the table, so it needs no statement of its own; the function does not,
    because nothing owns it, and leaving it behind would make the downgrade incomplete.
    """
    op.execute(DROP_USERS_TRIGGER)
    op.drop_table(USERS_TABLE_NAME)
    op.execute(DROP_TRIGGER_FUNCTION)
