"""The one MetaData every table hangs from, and the tables themselves.

Alembic compares this metadata against the database and repositories select from these Table
objects, so a column is declared in exactly one place. The naming convention names every index and
constraint from the table and column it covers, so a hand-written revision and an autogenerated
draft cannot disagree about what a constraint is called.

Enum types are declared with `create_type=False`, because each one is created and dropped by the
revision that introduces it rather than by whatever happens to reference it first.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.constants.billing import (
    BILLING_WEBHOOK_EVENT_STATUS_ENUM_NAME,
    USER_SUBSCRIPTION_STATUS_ENUM_NAME,
    BillingWebhookEventStatus,
    UserSubscriptionStatus,
)
from app.constants.idempotency import IDEMPOTENCY_KEY_STATE_ENUM_NAME, IdempotencyKeyState
from app.constants.user_roles import USER_ROLE_ENUM_NAME, UserRole

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
LOWER_EMAIL_INDEX_NAME = "ix_users_lower_email"

metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

user_role = postgresql.ENUM(
    *(role.value for role in UserRole), name=USER_ROLE_ENUM_NAME, create_type=False
)

users = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column("email", sa.Text(), nullable=False),
    sa.Column("password_hash", sa.Text(), nullable=False),
    sa.Column("role", user_role, nullable=False, server_default=UserRole.MEMBER.value),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
)

# Unique on the folded address rather than on `email`, so `A@x.com` and `a@x.com` are one account.
# Registration still stores the address as the user typed it; only the uniqueness test is folded.
sa.Index(LOWER_EMAIL_INDEX_NAME, sa.func.lower(users.c.email), unique=True)

# One row per signed-in browser. The cookie carries a random token and this table stores only its
# SHA-256, so a database leak does not hand over live sessions. `ON DELETE CASCADE` means deleting
# a user signs that user out everywhere without a second statement, and the index on `expires_at`
# is what lets the hourly cleanup job in slice 08 find expired rows without scanning the table.
user_sessions = sa.Table(
    "user_sessions",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column(
        "user_id",
        sa.Uuid(),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column(
        "last_seen_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Index("ix_user_sessions_expires_at", "expires_at"),
)

# One row per reset email. Like a session it stores only the SHA-256 of the token the email
# carries. `used_at` is set by the single statement that consumes it, the index on `user_id` serves
# the delete that retires a user's earlier unused resets, and the one on `expires_at` serves the
# cleanup job in slice 08.
user_password_resets = sa.Table(
    "user_password_resets",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column(
        "user_id",
        sa.Uuid(),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Index("ix_user_password_resets_user_id", "user_id"),
    sa.Index("ix_user_password_resets_expires_at", "expires_at"),
)

request_idempotency_key_state = postgresql.ENUM(
    *(state.value for state in IdempotencyKeyState),
    name=IDEMPOTENCY_KEY_STATE_ENUM_NAME,
    create_type=False,
)

# One claim per key and user, binding the key to the method, path, and body hash of the request
# that took it. `claim_token` names whichever request holds the claim now, so a superseded holder's
# completion or release, both scoped to its own token, changes nothing. The index on `created_at`
# serves the slice 08 cleanup of rows past the twenty-four hour replay window.
request_idempotency_keys = sa.Table(
    "request_idempotency_keys",
    metadata,
    sa.Column("key", sa.Text(), primary_key=True),
    sa.Column(
        "user_id",
        sa.Uuid(),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    sa.Column("request_method", sa.Text(), nullable=False),
    sa.Column("request_path", sa.Text(), nullable=False),
    sa.Column("request_body_hash", sa.Text(), nullable=False),
    sa.Column("state", request_idempotency_key_state, nullable=False),
    sa.Column("locked_until", sa.DateTime(timezone=True), nullable=False),
    sa.Column("claim_token", sa.Uuid(), nullable=False),
    sa.Column("status_code", sa.Integer(), nullable=True),
    sa.Column("response_body", postgresql.JSONB(none_as_null=True), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Index("ix_request_idempotency_keys_created_at", "created_at"),
)

user_subscription_status = postgresql.ENUM(
    *(status.value for status in UserSubscriptionStatus),
    name=USER_SUBSCRIPTION_STATUS_ENUM_NAME,
    create_type=False,
)

# One row per user holding the Stripe billing state the webhook last wrote. The customer and
# subscription ids are unique because the webhook finds a row by either, and nullable because a
# row can exist before Stripe has named both. Only the webhook writes this table.
user_subscriptions = sa.Table(
    "user_subscriptions",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column(
        "user_id",
        sa.Uuid(),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    ),
    sa.Column("stripe_customer_id", sa.Text(), nullable=True, unique=True),
    sa.Column("stripe_subscription_id", sa.Text(), nullable=True, unique=True),
    sa.Column("plan_id", sa.Text(), nullable=True),
    sa.Column(
        "status",
        user_subscription_status,
        nullable=False,
        server_default=UserSubscriptionStatus.INCOMPLETE.value,
    ),
    sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
    sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        "is_canceling_at_period_end", sa.Boolean(), nullable=False, server_default=sa.text("false")
    ),
    # The `created` time of the subscription event last applied; an older event is dropped.
    sa.Column("last_stripe_event_created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
)

billing_webhook_event_status = postgresql.ENUM(
    *(status.value for status in BillingWebhookEventStatus),
    name=BILLING_WEBHOOK_EVENT_STATUS_ENUM_NAME,
    create_type=False,
)

# One row per Stripe event delivered to the webhook: the idempotent ledger the claim upsert writes.
# The index on `attempted_at` serves the slice 08 cleanup of rows older than thirty days.
billing_webhook_events = sa.Table(
    "billing_webhook_events",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column("stripe_event_id", sa.Text(), nullable=False, unique=True),
    sa.Column("event_type", sa.Text(), nullable=False),
    sa.Column("status", billing_webhook_event_status, nullable=False),
    sa.Column(
        "attempted_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Index("ix_billing_webhook_events_attempted_at", "attempted_at"),
)
