"""The one MetaData every table hangs from, and the tables themselves.

Alembic compares this metadata against the database and repositories select from these Table
objects, so a column is declared in exactly one place. The naming convention names every index and
constraint from the table and column it covers, so a hand-written revision and an autogenerated
draft cannot disagree about what a constraint is called.

Enum types are declared with `create_type=False`, because each one is created and dropped by the
revision that introduces it rather than by whatever happens to reference it first.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.constants.user_roles import USER_ROLE_ENUM_NAME, UserRole

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
LOWER_EMAIL_INDEX_NAME = "ix_users_lower_email"

metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

user_role = postgresql.ENUM(
    *(role.value for role in UserRole), name=USER_ROLE_ENUM_NAME, create_type=False
)

users = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column("email", sa.Text(), nullable=False),
    sa.Column("password_hash", sa.Text(), nullable=False),
    sa.Column("role", user_role, nullable=False, server_default=UserRole.MEMBER.value),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
)

# Unique on the folded address rather than on `email`, so `A@x.com` and `a@x.com` are one account.
# Registration still stores the address as the user typed it; only the uniqueness test is folded.
sa.Index(LOWER_EMAIL_INDEX_NAME, sa.func.lower(users.c.email), unique=True)

# One row per signed-in browser. The cookie carries a random token and this table stores only its
# SHA-256, so a database leak does not hand over live sessions. `ON DELETE CASCADE` means deleting
# a user signs that user out everywhere without a second statement, and the index on `expires_at`
# is what lets the hourly cleanup job in slice 08 find expired rows without scanning the table.
user_sessions = sa.Table(
    "user_sessions",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column(
        "user_id",
        sa.Uuid(),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column(
        "last_seen_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Index("ix_user_sessions_expires_at", "expires_at"),
)

# One row per reset email. Like a session it stores only the SHA-256 of the token the email
# carries. `used_at` is set by the single statement that consumes it, the index on `user_id` serves
# the delete that retires a user's earlier unused resets, and the one on `expires_at` serves the
# cleanup job in slice 08.
user_password_resets = sa.Table(
    "user_password_resets",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column(
        "user_id",
        sa.Uuid(),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.Column("token_hash", sa.Text(), nullable=False, unique=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Index("ix_user_password_resets_user_id", "user_id"),
    sa.Index("ix_user_password_resets_expires_at", "expires_at"),
)
