"""The one MetaData every table hangs from, and the tables themselves.

Alembic compares this metadata against the database and repositories select from these Table
objects, so a column is declared in exactly one place. The naming convention names every index and
constraint from the table and column it covers, so a hand-written revision and an autogenerated
draft cannot disagree about what a constraint is called.

The `role` column is deliberately absent from `users`: the data model assigns it to slice 05, and
adding it here would put a column in the schema that nothing reads.
"""

import sqlalchemy as sa

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
LOWER_EMAIL_INDEX_NAME = "ix_users_lower_email"

metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

users = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
    sa.Column("email", sa.Text(), nullable=False),
    sa.Column("password_hash", sa.Text(), nullable=False),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    ),
)

# Unique on the folded address rather than on `email`, so `A@x.com` and `a@x.com` are one account.
# Registration still stores the address as the user typed it; only the uniqueness test is folded.
sa.Index(LOWER_EMAIL_INDEX_NAME, sa.func.lower(users.c.email), unique=True)
